# Generated by Django 5.2.6 on 2025-09-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0002_pet_produtoempresa_usuariocomum_usuarioempresarial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='imagem',
            field=models.ImageField(blank=True, default='defaults/pet.png', null=True, upload_to='pets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='produtoempresa',
            name='imagem',
            field=models.ImageField(blank=True, default='defaults/produto.png', null=True, upload_to='produtos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usuariocomum',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/avatar_comum.png', null=True, upload_to='usuarios/comum/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usuarioempresarial',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/avatar_empresa.png', null=True, upload_to='usuarios/empresa/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usuarioong',
            name='foto',
            field=models.ImageField(blank=True, default='defaults/avatar_ong.png', null=True, upload_to='usuarios/ong/%Y/%m/'),
        ),
    ]
