# Generated by Django 5.2.6 on 2025-09-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0003_pet_imagem_produtoempresa_imagem_usuariocomum_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adotado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outros', 'Outros')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='produtoempresa',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usuariocomum',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='usuarioempresarial',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='usuarioong',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
