# Generated by Django 5.2.6 on 2025-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0005_backfill_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
