# Generated by Django 5.2.6 on 2025-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0006_pet_slug_unique_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoempresa',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.AddIndex(
            model_name='produtoempresa',
            index=models.Index(fields=['slug'], name='AmigoFiel_p_slug_dbb8df_idx'),
        ),
        migrations.AddConstraint(
            model_name='produtoempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='uniq_produto_por_empresa'),
        ),
    ]
