# Generated by Django 5.2.6 on 2025-09-29 17:05

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0009_seed_more_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('-criado_em',)},
        ),
        migrations.AlterModelOptions(
            name='produtoempresa',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='usuariocomum',
            options={'ordering': ('user__username',)},
        ),
        migrations.AlterModelOptions(
            name='usuarioempresarial',
            options={'ordering': ('razao_social',)},
        ),
        migrations.AlterModelOptions(
            name='usuarioong',
            options={'ordering': ('nome_fantasia',)},
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea'), ('nao_inf', 'Não informado')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacinado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='produtoempresa',
            name='categoria',
            field=models.CharField(choices=[('racoes', 'Rações'), ('petiscos', 'Petiscos'), ('brinquedos', 'Brinquedos'), ('acessorios', 'Acessórios'), ('higiene', 'Higiene & Limpeza'), ('farmacia', 'Farmácia'), ('roupas', 'Roupas'), ('camas', 'Camas & Conforto'), ('areia', 'Areia/Litter'), ('transporte', 'Transporte'), ('treinamento', 'Treinamento'), ('outros', 'Outros')], db_index=True, default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('peixe', 'Peixe'), ('roedor', 'Roedor'), ('reptil', 'Réptil'), ('outros', 'Outros')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente a partir do nome.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='produtoempresa',
            name='estoque',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produtoempresa',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['especie'], name='AmigoFiel_p_especie_d6496c_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['adotado'], name='AmigoFiel_p_adotado_e7c8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['slug'], name='AmigoFiel_p_slug_a1fd96_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoempresa',
            index=models.Index(fields=['categoria'], name='AmigoFiel_p_categor_9434f3_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoempresa',
            index=models.Index(fields=['ativo'], name='AmigoFiel_p_ativo_d75062_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioempresarial',
            index=models.Index(fields=['cidade'], name='AmigoFiel_u_cidade_0aec81_idx'),
        ),
        migrations.AddIndex(
            model_name='usuarioong',
            index=models.Index(fields=['cidade'], name='AmigoFiel_u_cidade_f3d80e_idx'),
        ),
    ]
