# Generated by Django 5.2.6 on 2025-10-03 15:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0010_alter_pet_options_alter_produtoempresa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pago', max_length=20)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_doacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual_doacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor_doacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AmigoFiel.usuarioempresarial')),
                ('ong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AmigoFiel.usuarioong')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AmigoFiel.produtoempresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='AmigoFiel.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='AmigoFiel.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmigoFiel.produtoempresa')),
            ],
            options={
                'unique_together': {('carrinho', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='ParceriaOngEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias_ongs', to='AmigoFiel.usuarioempresarial')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcerias_empresas', to='AmigoFiel.usuarioong')),
            ],
            options={
                'unique_together': {('empresa', 'ong')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoOngVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_produtos', to='AmigoFiel.usuarioong')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_ong', to='AmigoFiel.produtoempresa')),
            ],
            options={
                'unique_together': {('produto', 'ong')},
            },
        ),
    ]
