# Generated by Django 5.2.6 on 2025-10-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0011_carrinho_pedido_itempedido_itemcarrinho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresarial',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/empresa/banner/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usuarioempresarial',
            name='slogan',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
