# Generated by Django 5.2.6 on 2025-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0012_add_empresa_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioong',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/ong/banner/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='usuarioong',
            name='slogan',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
