# Generated by Django 5.2.6 on 2025-10-17 02:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0013_add_ong_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoempresa',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produtoempresa',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
