# Generated by Django 5.2.7 on 2025-10-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0016_favorito'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorito',
            new_name='AmigoFiel_f_usuario_3c96cb_idx',
            old_name='AmigoFiel_f_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='favorito',
            new_name='AmigoFiel_f_pet_id_ed28e5_idx',
            old_name='AmigoFiel_f_pet_idx',
        ),
        migrations.RenameIndex(
            model_name='favorito',
            new_name='AmigoFiel_f_produto_bd138b_idx',
            old_name='AmigoFiel_f_produto_idx',
        ),
    ]
