# Generated by Django 5.2.6 on 2025-11-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0018_seed_users_and_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='retirado',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
