# Generated by Django 5.2.6 on 2025-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0019_itempedido_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomum',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
