# Generated by Django 5.2.6 on 2025-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0020_usuariocomum_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresarial',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuarioong',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
