# Generated by Django 5.2.6 on 2025-11-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmigoFiel', '0021_usuarioempresarial_cep_usuarioong_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomum',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='usuarioempresarial',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='usuarioong',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
